***
# The numpy.random Package in Python
**Student Name:** Gillian Kane-McLoughlin | 
**Student Number:** G00398258 | 
**Due Date:** 22nd November 2021

***

#### Overview
This notebook will contain my submission for the Programming for Data Analysis practical assignment for Winter 2021

<br>

***

#### Required Modules

In [1]:
import numpy as np

***

#### Task 1: Explain the overall purpose of the package

According to the official documentation, NumPy or numerical Python is the fundamental package for scientific computing in Python [5]. This Python library not only provides a multidimensional array object, but also various derived objects including matrices and masked arrays, as well as routines for performing fast operations on arrays such as sorting, basic linear algebra and statistical operations, random simulation, etc. [5]. The NumPy Python library provides us with what Real Python describes as a simple yet powerful data structure - the n-dimensional array [7]. 

Within the overall NumPy package, the random module, accessed using the basic function numpy.random(), implements pseudo-random number generators for various distributions, including uniform, normal, and negative exponential [2]. There are two components to generating random numbers: the BitGenerator, which manages state and provides functions to produce random doubles and random unsigned 32- and 64-bit values, and the random generator, which takes the bit generator-provided stream and transforms them into more useful distributions [7]. The Generator, a user-facing object, accepts a bit generator instance as an argument [7]. The default generator is currently PCG64 (Permuted Congruential Generator) [6], but an older generator MT19937 (Mersenne Twister) can also be accessed, although this is not recommended [7] 

***

#### Task 2: Explain the use of the “Simple random data” and “Permutations” functions

<br>

#### **1) Simple Random Data**
***

There are ten different simple random data functions available in the numpy.random package for generating pseudo random numbers, some of which are aliases for each other and others that are deprecated:

- rand(d0, d1, ..., dn)  
- randn(d0, d1, ..., dn)  
- randint(low[, high, size])
- random_integers(low[, high, size])
- random_sample([size])
- random([size])
- ranf([size])
- sample([size])
- choice(a[, size, replace, p])
- bytes(length)

Lets take a look at each of these functions in turn, and see what the syntax looks like, the paramaters and outputs for each as per numpy.org, and some practical examples of the code in use.

<br>

#### **numpy.random.rand**
***

`random.rand(d0, d1, ..., dn)`

As per the official documentation, this function returns values in a given shape by creating an array of the given shape and populating it with random samples from a uniform distribution (values between 0 & 1).

**_Parameters:_** d0, d1, …, dnint, optional  
The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

**_Returns:_** outndarray, shape (d0, d1, ..., dn)  
Random values.

In [2]:
# Examples of numpy.random.rand - generate a 7 x 3 array of random numbers
np.random.rand(7,3)

array([[0.17406634, 0.48754589, 0.2780417 ],
       [0.12133685, 0.54139527, 0.4635558 ],
       [0.88938101, 0.48112217, 0.54489788],
       [0.67603859, 0.67186943, 0.7073633 ],
       [0.60834465, 0.2125483 , 0.38887439],
       [0.64004342, 0.47093976, 0.940239  ],
       [0.08181834, 0.24884682, 0.90294487]])

In [3]:
# Generate a random float
np.random.rand()

0.27692421990879257

_References_: [3], [6]

<br>

#### **numpy.random.randn**
***

`random.randn(d0, d1, ..., dn)`

This function returns a sample or samples from the standard normal distribution.

The randn function will generate an array with the shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 if positive int_like arguments are inputted, and will return a single float randomly sampled from the distribution if no argument is provided.

**_Parameters:_** d0, d1, …, dnint, optional  
The dimensions of the returned array must be non-negative. If no argument is given a single Python float is returned.

**_Returns:_** Z: ndarray or float  
A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, or a single such float if no parameters were supplied.

In [4]:
# Examples of numpy.random.randn
np.random.randn()

1.0359016371375076

In [5]:
np.random.randn(3)

array([-0.54214352,  0.17707411, -0.40856656])

In [6]:
# Two-by-four array of samples from N(3, 6.25):
3 + 2.5 * np.random.randn(2, 4)

array([[ 2.91586048, -0.23170119,  5.53368659,  1.71330058],
       [ 2.24552367,  6.23990431,  4.50154762,  3.73186739]])

_References_: [3], [6]

<br>

#### **numpy.random.randint**
***

`random.randint(low, high=None, size=None, dtype=int)`

This function returns random integers from low (inclusive) to high (exclusive) from the discrete uniform distribution of the specified dtype in the “half-open” interval [low, high).

The documenatation states that if high is None (which is the default), then the results are from [0, low).

**_Parameters:_**  lowint or array-like of ints  
Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).

**_Optional:_** highint or array-like of ints  
If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values

**_Optional:_** sizeint or tuple of ints  
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

**_Optional:_** dtypedtype    
Desired dtype of the result. Byteorder must be native. The default value is int.

**_Returns:_** outint or ndarray of ints    
size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

In [7]:
# Examples of numpy.random.randint
np.random.randint(2, size=5)

array([1, 1, 1, 0, 0])

In [8]:
# Generate a 1 x 3 array with 3 different upper bounds
np.random.randint(1, [5, 7, 9])

array([3, 5, 5])

In [9]:
# Generate a 3 x 6 array of ints between 0 and 6, inclusive:
np.random.randint(7, size=(3, 6))

array([[5, 0, 0, 6, 1, 1],
       [2, 5, 0, 3, 0, 3],
       [4, 2, 1, 0, 3, 5]])

_References_: [3], [6]

<br>

#### **numpy.random.random_integers**
***

`random.random_integers(low, high=None, size=None)`

This function returns random integers of type np.int_ between the low and high parameters provided, inclusive, from the discrete uniform distribution in the closed interval [low, high]. 

If high is None (the default), then the results outputted are from [1, low]. The np.int_ type translates to the C long integer type and its precision is platform dependent.

As per the official documentation, the numpy.random.random_integers function has been deprecated. Users are advised to use the randint function instead (see heading above).

**_Parameters:_** lowint  
Lowest (signed) integer to be drawn from the distribution (unless high=None, in which case this parameter is the highest such integer).

**_Optional:_** highint  
If provided, the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None).

**_Optional:_** sizeint or tuple of ints  
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

**_Returns:_** outint or ndarray of ints  
size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

_Note: I received a warning message when testing out this function as it is deprecated. Please see the message below and example of the same function using randint_

In [10]:
# Examples of numpy.random.random_integers
np.random.random_integers(6)

<ipython-input-10-071506707e34>:2: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  np.random.random_integers(6)


6

In [11]:
np.random.randint(1,6+1)

5

_References_: [3], [6]

<br>

#### **numpy.random.random_sample, numpy.random.random, numpy.random.ranf & numpy.random.sample**
***

`random.random_sample(size=None) | random.random(size=None) | random.ranf() | numpy.random.sample(size=None)`

These functions return random floats in the half-open interval (meaning from 0 to 1, where 1 is excluded).

As per the official documentation, **numpy.random.random**, **numpy.random.ranf** and **random.random.sample** are aliases for the **random.random_sample** function, whose results are taken from the continuous uniform distribution over the stated interval, based on the following formula:

A possible use case for this function would be for lotteries or raffles, where a winner or winners needs to be drawn from a list of entries.

`(b - a) * random_sample() + a`

**_Parameters:_** sizeint or tuple of ints, optional  
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

**_Returns:_** outfloat or ndarray of floats  
Array of random floats of shape size (unless size=None, in which case a single float is returned).

In [12]:
# Examples 0f numpy.random.random_sample
np.random.random_sample()

0.07604315119662941

In [13]:
# Generate a 3 x 2 array of random numbers from [-5, 0)
5 * np.random.random_sample((3, 2)) - 5

array([[-3.25007673, -2.07672609],
       [-2.80623771, -4.1746448 ],
       [-1.87441992, -3.18530116]])

_References_: [3], [6], [13]

<br>

#### **numpy.random.choice**
***

`random.choice(a, size=None, replace=True, p=None)`

This function generates a random sample from a given 1-D array. It takes an array as a parameter and randomly returns one of the values in that array, making it another option for use cases such as lottery or raffle draws.

**_Parameters:_** a: 1-D array-like or int  
If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if it were np.arange(a)

**_Optional:_** sizeint or tuple of ints  
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

**_Optional:_** replaceboolean  
Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.

**_Optional:_** p1-D array-like  
The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

**_Returns:_** samples: single item or ndarray
The generated random samples

**_Raises:_** ValueError  
If a is an int and less than zero, if a or p are not 1-dimensional, if a is an array-like of size 0, if p is not a vector of probabilities, if a and p have different lengths, or if replace=False and the sample size is greater than the population size

In [14]:
# Examples of numpy.random.choice
np.random.choice(5, 3)

array([0, 4, 3])

In [15]:
# Generate a non-uniform random sample from np.arange(7) of size 5:
np.random.choice(7, 5, p=[0.2, 0, 0.1, 0, 0.3, 0.4, 0]) # probability must be equal to 1

array([5, 4, 0, 5, 5])

_References_: [3], [6], [14]

<br>

#### **numpy.random.bytes**
***

`random.bytes(length)`

This function returns a string of random bytes.

**_Parameters:_** length: int  
Number of random bytes.

**_Returns:_** out: bytes  
String of length length.

In [16]:
# Example of numpy.random.bytes
np.random.bytes(13)

b'\xbf\x93\xc2\xfe\xd5\x06Fr\x9f\x8as\x98|'

_References_: [3], [6]

<br>

#### **2) Permutations**
***

There are two permutation functions available in the numpy.random package:

- shuffle() &
- permutation()

These functions allow us to arrange the elements in an array, but have different effects. Lets look at these two functions separately.

<br>

#### **numpy.random.shuffle**
***

`random.shuffle(x)`

The shuffle function will modify a sequence in-place by shuffling its contents.

It only shuffles the array along the first axis of a multi-dimensional array and although the order of sub-arrays is changed, their contents remain the same.

**_Parameters:_** x: ndarray or MutableSequence  
The array, list or mutable sequence to be shuffled.

**_Returns:_** None

In [17]:
# Example of numpy.random.shuffle
arr = [1,6,3,[6],2]
np.random.shuffle(arr)
arr

[6, [6], 1, 2, 3]

_References_: [6], [14]

<br>

#### **numpy.random.permutation**
***

`random.permutation(x)`

The permutation function will randomly permute (or rearrange) a sequence, or return a permuted range.
If x is a multi-dimensional array, it will only be shuffled along its first index.

The difference between the permutation function and the shuffle function discussed above is that permutation() rearranges the array, but does not change or overwrite the original array, while the shuffle function changes the original array.

**_Parameters:_** x: int or array_like
If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.

**_Returns:_** out: ndarray
Permuted sequence or array range.

In [18]:
# Examples of numpy.random.permutation
np.random.permutation(5)

array([3, 4, 2, 0, 1])

In [19]:
# Permute a given sequence
np.random.permutation([9,7,1,4,6])

array([7, 9, 1, 6, 4])

_References_: [6], [14]

<br>

***

#### Task 3: Explain the use and purpose of at least five “Distributions” functions

**1. Normal Distribution**

You can't discuss generating random numbers without discussing normal distribution [10].

#### References
[] https://www.datacamp.com/community/tutorials/numpy-random  
[2] https://docs.python.org/3/library/random.html  
[3] https://het.as.utexas.edu/HET/Software/Numpy/reference/routines.random.html   
[] https://www.javatpoint.com/numpy-random  
[] https://linuxhint.com/use-python-numpy-random-function/  
[6] https://numpy.org/  
[6]https://numpy.org/doc/stable/reference/random/bit_generators/pcg64.html  
[7] https://numpy.org/doc/stable/reference/random/index.html?highlight=random%20sampling%20numpy%20random#module-numpy.random  
[] https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html  
[] https://pythonguides.com/python-numpy-random/  
[7] https://realpython.com/numpy-tutorial/  
[] https://www.sharpsightlabs.com/blog/numpy-random-seed/  
[] https://www.studytonight.com/post/creating-random-valuedarrays-in-numpy  
[11] https://towardsdatascience.com/random-numbers-in-numpy-[6]9172d6eac16  
[] https://towardsdatascience.com/random-seed-numpy-7[6]6cf7[6]76a5f  
[13] https://towardsdatascience.com/statistics-in-python-generating-random-numbers-in-python-numpy-and-sklearn-60e16b2210ae  
[14] https://www.w3schools.com/python/numpy/numpy_random.asp  
[] https://www.w3schools.com/python/numpy/numpy_random_permutation.asp  
[] https://web.physics.utah.edu/~detar/lessons/python/random/node2.html  
[] https://www.pythonpool.com/numpy-random-permutation/  